CREATE TABLE projects (id INTEGER PRIMARY KEY,title TEXT, catagory INTEGER,funding_goal INTEGER, start_date INTEGER, end_date INTEGER);
CREATE TABLE users (id INTEGER PRIMARY KEY);
CREATE TABLE pledges (id INTEGER PRIMARY KEY);
